### ISSUE TITLE
Issue with: StoryBoard() with empty children: [] and customLanes: [...]

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#14]
When using StoryBoard() as a widget in a MaterialApp app with customLanes: [...] you often want children: [] to be empty as they are set via the customLanes: [...]. 
However, if children is empty, a lane is still drawn for it and it lane heading text "children" is written out, and actually on top of the first customLane.

Tested in version: 0.1.2+1

**Comment by rodydavis** [comment]
Fixed on version 0.1.3

**Comment by rydmike** [comment]
Tested and works ok, as long as you set children to null (or leave it out completely of course). 

If you leave children in there as an empty list [] (which I had since it was @required in previous text), then it the lane is correctly gone, however the lane header text "Children" for the Children lane is still present and overwrites the next lane header. Since children can now be removed/be null, it is of course unlikely that anybody would provide an empty children list to see this minor residual issue.
